class_name SpriteMeta
extends RefCounted
## Generated by tools/sprites/build.py. Atlas layout of each character sprite:
## anim -> [first row, frames, directions]. Frames are 64px.

const ATLASES := {
	"crusader": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"skeleton": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"ghoul": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"skeleton_warrior": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"lich": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"dragonborn": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"stormcaller": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"werewolf": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"chainwarden": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"frost_witch": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"rune_golem": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"wraith_knight": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"necromancer": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"chronomancer": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"draugr": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"ice_wraith": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"draugr_warrior": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"frost_mage": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"draugr_king": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"bog_zombie": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"sackhead": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"bog_brute": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"plague_witch": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"mother_rot": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"skeleton_mage": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
}
