class_name SpriteMeta
extends RefCounted
## Generated by tools/sprites/build.py. Atlas layout of each character sprite:
## anim -> [first row, frames, directions]. Frames are 64px.

const ATLASES := {
	"crusader": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"skeleton": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"ghoul": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"skeleton_warrior": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "slash": [4, 6, 4], "hurt": [8, 6, 1]}},
	"lich": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
	"skeleton_mage": {"cols": 9, "rows": 9, "anims": {"walk": [0, 9, 4], "spellcast": [4, 7, 4], "hurt": [8, 6, 1]}},
}
